### ISSUE TITLE
Upgrade to play-redis 2.3.0 from 2.1.2 throwing No implementation for play.cache.SyncCacheApi exception 

### ISSUE THREAD

**Issue by tech-sam** [KarelCemus/play-redis#229] opened 2020-04-24 06:05 UTC
### Version
1. Version of Java : 1.8_181
1. Version of play-redis : 2.3.0
1. Version of Play : 2.6

### Custome Cache module sample 

```
public class CustomeCacheModule extends AbstractModule {

	List<String> namedCaches = new ArrayList<String>(Arrays.asList("options-cache", "user-cache", "session-cache", "api-token-cache"));

	@Override
	protected void configure() {
		Provider<SyncCacheApi> syncCacheApi = getProvider(Key.get(SyncCacheApi.class, Names.named("custome-default")));

		bind(SyncCacheApi.class).toInstance(new CustomeSyncCacheApi(syncCacheApi,"custome-default"));
		namedCaches.forEach(cache -> {
			bind(SyncCacheApi.class).annotatedWith(new NamedCacheImpl(cache))
					.toInstance(new DefaultSyncCacheApi(syncCacheApi, cache));
		});
		Provider<CacheApi> cacheProvider = getProvider(Key.get(CacheApi.class, Names.named("custome-default")));
		bind(CacheManager.class).toInstance(new CacheManager(cacheProvider));
	}
}

```

I am passing SyncCacheApi provider to Custom SyncCacheApi implementation classes.
After upgrading to **2.3.0** from **2.1.2**  getting the exception . 

```
1) No implementation for play.cache.SyncCacheApi annotated with @com.google.inject.name.Named(value=custome-default) was bound.
  at com.greytip.adrem.CustomeCacheModule.configure(GtCacheModule.java:26) (via modules: com.google.inject.util.Modules$OverrideModule -> com.greytip.adrem.CustomeCacheModule)

2) No implementation for play.api.cache.redis.CacheApi annotated with @com.google.inject.name.Named(value=custome-default) was bound.
  at com.greytip.adrem.CustomeCacheModule.configure(CustomeCacheModule.java:35) (via modules: com.google.inject.util.Modules$OverrideModule -> com.greytip.adrem.CustomeCacheModule)

2 errors]
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:193)
        at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:125)
        at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:281)
        at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:173)
        at akka.stream.impl.fusing.MapAsyncUnordered$$anon$31.onPush(Ops.scala:1375)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:523)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:409)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
        at akka.actor.Actor.aroundReceive(Actor.scala:539)
        at akka.actor.Actor.aroundReceive$(Actor.scala:537)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
        at akka.actor.ActorCell.invoke(ActorCell.scala:581)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at kamon.instrumentation.executor.ExecutorInstrumentation$InstrumentedForkJoinPool$TimingRunnable.run(ExecutorInstrumentation.scala:653)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:49)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
```
I have verified the [migration guide](https://github.com/KarelCemus/play-redis/blob/2.3.0/doc/40-migration.md) did'nt find any breaking changes apart from @ Named annotation deprication and removal from 2.1.0 . 

Any suggestion is helpful.

**Comment by KarelCemus** [comment] 2020-04-24 06:45
Your custom module does not register anything to `SyncCacheApi @Named("custome-default")`. So I assume that it gets registered through the configuration. Could you share it for revision?

**Comment by tech-sam** [comment] 2020-04-24 06:59
Thanks for the quick response Karel,  here is the configuration
```
play.cache.redis {
  default-cache:  "custome-default"
  bind-default: false
  instances {
    custome-default {
      source:     standalone
      host:       ${redis_host}
      port:       ${redis_port}
      database:   ${cache_database}

    }
  }
}
```

**Comment by KarelCemus** [comment] 2020-04-24 07:04
It looks ok. And is play-redis module enabled? You must have in your config the following line:

```
play.modules.enabled += "play.api.cache.redis.RedisCacheModule"
```

**Comment by tech-sam** [comment] 2020-04-24 07:41
without this earlier version also should not work which I am using from almost 2 years  :wink:

```
play {
  modules {
    enabled += "play.api.cache.redis.RedisCacheModule"
  }
}


```
The main reason for upgrading to **2.3.0**  is I am getting constant timeout exceptions in production AWS environment which is causing performance issues,

```
java.util.concurrent.TimeoutException: Futures timed out after [1 second]
    at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
    at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
    at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:172)
    at akka.dispatch.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3641)
    at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:170)
    at scala.concurrent.Await$.result(package.scala:142)
    at play.api.cache.redis.impl.Builders$SynchronousBuilder$.$anonfun$toResult$1(Builders.scala:50)
    at scala.util.Try$.apply(Try.scala:209)
    at play.api.cache.redis.impl.Builders$SynchronousBuilder$.toResult(Builders.scala:50)
    at play.api.cache.redis.impl.dsl$RecoveryUnitFuture$.recoverWithDone$extension(dsl.scala:42)
    at play.api.cache.redis.impl.RedisCache.$anonfun$removeMatching$1(RedisCache.scala:84)
    at play.api.cache.redis.impl.dsl$CacheKey$.prefixed$extension(dsl.scala:50)
    at play.api.cache.redis.impl.RedisCache.removeMatching(RedisCache.scala:83)

**Comment by KarelCemus** [comment] 2020-04-24 07:46
Well, I browsed the changelog and there is anything, which should break your code. Since everything looks good, could you provide a minimal example to reproduce this issue? 

The timeout is usually caused by incorrect use of `getOrElse` mechanism, which is already discussed somewhere in this issue tracker. The timeout is end-to-end and if you include some long-running task into that `else` part, it can result in this exception. However, I think (but not sure atm) that it an issue only of sync version of the API since there is an `await` under the hood to convert async result to sync.

Hope this is clear

**Comment by KarelCemus** [comment] 2020-04-24 08:06
Check out this configuration:

```
  # synchronization timeout applies only with synchronous API. It does not
  # apply with asynchronous API and you are free to ignore it. This value
  # is used with `Await.result`.
  #
  # note: this is global definition, can be locally overriden for each
  # cache instance. To do so, redefine this property
  # under 'play.cache.redis.instances.instance-name.this-property'.
  #
  sync-timeout:     1s
```

This might be what you are actually looking for

**Comment by KarelCemus** [comment] 2020-05-02 21:05
Sorry for late response, I was busy. However, checked your repo and the issue is pretty simple. See [CHANGELOG](https://github.com/KarelCemus/play-redis/blob/master/CHANGELOG.md#link-210) especially the migration notes in version `2.1.0`, which is the minor you were using.

> Removal of @Named and introduction of @NamedCache
Named caches now uses @NamedCache instead of @Named to be consistent with Play's EhCache and enable interchangeability of the implementation.
> 
> Migration: Change the annotation where necessary.
>
>
> Backward compatibility: In simple scenarios, there should be no breaking changes. Use of @Named was deprecated and should emit warning in logs, but the binding should still work. The warnings can be disabled through the logger configuration, though the support will be fully removed in the 2.2.0. The complex scenarios with the custom RedisInstance or RedisCaches have to be migrated right away, there is no fallback binding.

As you can see, the `@Named` was deprecated in 2.1.0 but still worked. Then it was removed in 2.2.0 and no longer works in 2.3.0. However, your [code in the repo](https://github.com/tech-sam/play-redis/blob/master/app/config/CustomCacheModule.java#L22) is:

```scala
Provider<SyncCacheApi> syncCacheApi = getProvider(Key.get(SyncCacheApi.class, Names.named("custom-default")));
```

where `Names.named` produces `@Named`, which obviously no longer works. Changing it into `new NamedCacheImpl`, which you have a few lines below,  fixes your issue.

**Comment by KarelCemus** [comment] 2020-05-09 17:29
I assume this resolved your issue and closing this ticket. If you feel otherwise or have further questions, feel free to reopen it.

**Closed by KarelCemus** 2020-05-09 17:29 UTC
