### ISSUE TITLE
Connection flood / Too many threads

### ISSUE THREAD

**Issue by djole103** [KarelCemus/play-redis#188] opened 2018-10-09 19:20 UTC
### Reporting a bug?
1. Version of play-redis - 2.0.2
1. Version of Scala - 2.12
1. Version of Play - 2.6.12

Added a `cacheApi` dependency into the build.sbt which pulled this project.
With ```implicit @Named("redis") cache: CacheAsyncApi``` in the class definition any `cache.get(...)` will get the value but the connection is never closed/reused. 

As the applications continue to run I get a flood of redis connections and ultimately ``` [application-akka.actor.default-dispatcher-2154] [akka://application/syst
em/IO-TCP/selectors/$a/1] Accept error: could not accept new connection
java.io.IOException: Too many open files```

I see that my setup would lead to using https://github.com/etaty/rediscala and the `RedisClient` class, but I don't see anywhere those connections are managed. 

Suggestions? Help?

Thanks

**Comment by KarelCemus** [comment] 2018-10-09 21:50
This looks more like an issue with rediscala, not play-redis. However, it is difficult to say, can you provide steps to reproduce your issue? You talk about some "your setup", what it means?

Play-redis uses `RedisClient` internally as a singleton so there should not be any issue, unless it is a bug directly in the `RedisClient` itself.

> but I don't see anywhere those connections are managed.

`RedisClient` uses [`RedisClientActor`](https://github.com/etaty/rediscala/blob/55573df26adbe20be54291ffc67414af028bf889/src/main/scala/redis/Redis.scala#L38) to manage the connection

Since you have an issue with connections, you might take a look at [RedisClientActor](https://github.com/etaty/rediscala/blob/55573df26adbe20be54291ffc67414af028bf889/src/main/scala/redis/actors/RedisClientActor.scala#L22) or even [RedisWorkerIO](https://github.com/etaty/rediscala/blob/55573df26adbe20be54291ffc67414af028bf889/src/main/scala/redis/actors/RedisWorkerIO.scala#L15), which manages the connection


I am not sure if this helps you but you must provide additional details to reproduce your issue, otherwise I am unable to help you.

**Comment by djole103** [comment] 2018-10-09 22:12
If you create a standard/simple play controller that makes a redis request on every call, do you see a rising number of redis connections?

**Comment by KarelCemus** [comment] 2018-10-09 22:13
No, everything works like a charm .... I use redis in about 20 production applications

**Comment by djole103** [comment] 2018-10-09 22:20
This play-redis repo in 20 production applications? Hmm... Looking at rediscala I can't find anywhere they close the connection after data transfer. Do you have any suspicions as to why I might be seeing connections not being closed?

Thank you for the help

On Oct 9, 2018, at 6:13 PM, Karel Čemus <notifications@github.com<mailto:notifications@github.com>> wrote:


No, everything works like a charm .... I use redis in about 20 production applications

**Comment by KarelCemus** [comment] 2018-10-09 22:32
Yes, ...and consider other contributors and github stars, nobody has major issues.

Maybe redis closes connection? And it is not properly cleaned up? I don't know but I believe it is specific to your environment

**Comment by djole103** [comment] 2018-10-09 22:33
I believe you. If that's the case it's definitely something specific to my environment. I'm just wondering what might be the cause given that I am getting values back for my redis queries but connections are still not being closed.

**Comment by KarelCemus** [comment] 2018-10-09 22:41
I'd guess that your redis closes connections instead of keeping them established.... properly misconfigured? And it is possible that rediscala does not properly clean up old connections, which might lead to your issues considering the number of connections. Although... this is just a hypothesis, it needs to be elaborated. Otherwise, without additional clues, I don't have any other idea, though I'm not an expert on redis, sorry.

**Comment by KarelCemus** [comment] 2018-10-11 10:52
Closing for now as it seems that it is not issue of play-redis. If you come will new details, feel free to reopen this issue.

**Closed by KarelCemus** 2018-10-11 10:52 UTC

**Comment by edrevo** [comment] 2021-04-13 06:25
@djole103, did you ever find out the root cause of this? I am seeing similar issues.
