### ISSUE TITLE
repository not available

### ISSUE THREAD

**Issue by mleprince** [KarelCemus/play-redis#23] opened 2015-11-15 21:42 UTC
Hi,

The Brando repository is not avaible when I run the compilation. Any idea ?

My application.conf : 

resolvers += "chrisdinn" at "http://chrisdinn.github.io/releases/"
libraryDependencies += "com.digital-achiever" %% "brando" % "3.0.2"
libraryDependencies += "com.github.karelcemus" %% "play-redis" % "0.3-SNAPSHOT"

SBT error : 

sbt.ResolveException: unresolved dependency: com.github.karelcemus#play-redis_2.11;0.3-SNAPSHOT: not found

**Comment by KarelCemus** [comment] 2015-11-15 21:52
Hi,

> libraryDependencies += "com.digital-achiever" %% "brando" % "3.0.2"

I wouldn't recommend you using version 3, it won't work. API has significantly changed so you won't start it up. And I have not upgraded to v3 yet as it has some significant behavior changes I need to resolve first. See [here](https://github.com/chrisdinn/brando/issues/60). Then I'll upgrade to v3.

Regarding the missing dependency, it's weird. I deploy it into sonatype repository which should be included in your resolvers by default. The only thing it occurs to me is that snapshots are disabled by default and you are using a snapshot version. I'd suggest you to add the following line:

```
resolvers += Resolver.sonatypeRepo("snapshots")
```

Otherwise look [here](http://www.scala-sbt.org/0.13/docs/Resolvers.html)

Hope it helps. Let me know

**Comment by Enalmada** [comment] 2015-11-17 07:12
I created a fresh play 2.4.3 project and followed the readme doc and get the same "com.github.karelcemus#play-redis_2.11;0.3-SNAPSHOT: not found" error.  

Tried adding snapshot resolver...
```
[error] Server access Error: Connection refused: connect url=https://oss.sonatype.org/content/repositories/snapshots/com/github/karelcemus/play-redis_2.11/0.3-SNAPSHOT/maven-metadata.xml
[error] Server access Error: Connection refused: connect url=https://oss.sonatype.org/content/repositories/snapshots/com/github/karelcemus/play-redis_2.11/0.3-SNAPSHOT/play-redis_2.11-0.3-SNAPSHOT.pom
```

Some sort of permissions issue on your maven files?

**Comment by KarelCemus** [comment] 2015-11-17 07:56
@Enalmada I also created a fresh play 2.4.3 to reproduce yor issues. 

I confirm that readme guide is not working, the repository is trully missing. However, adding the snapshot resolver fixed it for me.

I also checked the sonatype repository and everything seems to be alright. Please, check yourself.

[pom.xml](https://oss.sonatype.org/service/local/repositories/snapshots/content/com/github/karelcemus/play-redis_2.11/0.3-SNAPSHOT/play-redis_2.11-0.3-SNAPSHOT.pom)
[repository](https://oss.sonatype.org/#nexus-search;quick~com.github.karelcemus)

**Comment by Enalmada** [comment] 2015-11-17 08:27
Silly question...if you click those links in your browser can you see them?  If I click those links in my browser I get "Connection refused" just like I see in the activator dependency step but I am not sure if it is legit to see those in browser or not.  If you can click those links and they work then perhaps you are authenticated somehow that the public is not?  Unfortunately I know nothing about sonatype and dependencies so just brainstorming.  

I tried again just to be sure and both the short form resolvers += Resolver.sonatypeRepo("snapshots") and the full resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots" and both give me connection refused like I posted above.

**Comment by Enalmada** [comment] 2015-11-17 08:31
If I build your code locally with activator publish-local everything works...I can put the result in my lib folder.  But I am curious if this problem is just me or not  Can you humor me and delete ~/.ivy2/local/com.github.karelcemus dir and then try again to see if that triggers the problem?   If you have ever done a publishLocal then it wouldn't be trying to pull dependencies from the remote avoiding the connection issue perhaps...

**Comment by KarelCemus** [comment] 2015-11-17 08:31
Yes, I see them and I'm not authenticated. I can open them also in the "Anonymous window" in Chrome.

Sonatype is free maven repo for open source projects

**Comment by KarelCemus** [comment] 2015-11-17 08:33
I know that, I deleted it before I tried to reproduce it. That is how I confirmed the missing resolver thing. But when I added the snapshots resolver it successfully downloaded the lib.

Plus I have several collegues who successfully using v2 of this lib in Sonatype so I do not expect any issue here

**Comment by KarelCemus** [comment] 2015-11-17 08:36
Look [here](https://oss.sonatype.org/content/repositories/snapshots/com/github/karelcemus/play-redis_2.11/0.3-SNAPSHOT/) Everything is here and publicaly available.

**Comment by Enalmada** [comment] 2015-11-17 08:40
Ok well that motivated me to try anonymous too...and strangely every browser gives me connection refused.  But...I clicked the links on my phone and they work.  So there is no doubt that my computer is the problem somehow.  Thanks for taking the time to confirm public access.  I am truly stumped at why I would only be having connection refused for play-redis when everything else seems to work but I must admit this is on me to debug somehow...so strange...

**Comment by KarelCemus** [comment] 2015-11-17 08:49
Sorry for that you might try to google it. Sonatype should not cause any issues.

However I'm glad it seems the repository itself is fine.

@mleprince  Could you please confirm the snapshots resolver fixes the issue for you? I'd updated README and closed this.

**Comment by mleprince** [comment] 2015-11-17 09:02
Hi,
I added the Sonatype resolver, everything works fine. Thanks

**Closed** 2015-11-17 09:14 UTC
